import type { Metadata } from 'next'
import { Jost } from 'next/font/google'
import TRPCProvider from './_trpc/TRPCProvider'

import '../scss/main.scss'

const jost = Jost({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <TRPCProvider>
          {children}
        </TRPCProvider>
      </body>
    </html>
  )
}
